

-- ************************************************************
-- posts table
-- ************************************************************
insert into posts
  (owner_id, text_body, time_posted, is_helper, is_helped, status_field, active, skill_ids)
values
  (5, 'I need a website. How much will it cost can you turn it around in photoshop so we can see more of the front, and we dont need a backup, it never goes down! labrador make the font bigger. Can you rework to make the pizza look more delicious use a kpop logo thats not a kpop logo!.', '2021-01-16T19:59:23Z', true, false, 'active', true, {3, 2, 6}),
  (6, 'I need a website. How much will it cost can you turn it around in photoshop so we can see more of the front, and we dont need a backup, it never goes down! labrador make the font bigger. Can you rework to make the pizza look more delicious use a kpop logo thats not a kpop logo!', '2021-01-21T06:06:33Z', false, true, 'active', true, {1, 3, 7, 4}),
  (1, 'I would love to help someone who would want to learn Yoga. I have a few years worth of experience as a developer and would love to have someone to mentor. ', '2021-01-18T07:44:28Z', true, false, 'active', true, {2, 12, 9, 3}),
  (1, 'Inredibly excited for the new PS4 release!!!! What do you guys think about that? ', '2021-01-09T20:28:12Z', true, false, 'active', true, { 4, 6, 15}),
  (1, 'Mentorship is the best way to reinforce knowledge. Is anyone looking for a mentor to help them setup Writing backend? Would love to offer some help. ', '2021-01-23T23:57:47Z', true, false, 'active', true, {2}),
  (3, 'My grasp on reality right now is tenuous. We want to see more charts. Are we in agreeance. Performance review prairie dogging run it up the flagpole, ping the boss and circle back five-year strategic plan herding cats. Low hanging fruit circle back nor due diligence optics usabiltiy. Deploy to production. The last person we talked to said this would be ready we need to build it so that it scales, this is not the hill i want to die on clear blue water scope creep nor we want to see more charts.', '2021-01-05T07:26:13Z', false, true, 'active', true, {2, 8),
  (7, 'Work. Strategic staircase we need distributors to evangelize the new line to local markets. Circle back around i also believe its important for every member to be involved and invested in our company and this is one way to do so yet reach out, and i am dead inside, or personal development note for the previous submit: the devil should be on the left shoulder. Game plan due diligence, for can you send me an invite?. You must be muted create spaces to explore what’s next put a record on and see who dances, so poop', '2021-01-13T19:39:38Z', true, false, 'active', true, {5}),
  (2, 'Drop-dead date can you send me an invite? service as core &innovations as power makes our brand i don''t want to drain the whole swamp, i just want to shoot some alligators who''s the goto on this job with the way forward . Helicopter view land the plane but products need full resourcing and support from a cross-functional team in order to be built, maintained, and evolved but performance review zeitgeist keep it lean we need a paradigm shift.', '2021-01-29T14:03:23Z', false, true, 'active', true, {7, 4}),
  (1, 'I was wondering if my cat could be placed over the logo in the flyer. That will be a conversation piece can you make the logo bigger yes bigger bigger still the logo is too big can we barter services? yet labrador so we need to make the new version clean and sexy can you pimp this powerpoint, need more geometry patterns you might wanna give it another shot.', '2021-02-01T19:32:18Z', true, false, 'active', true, {4}),
  (6, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2021-01-05T08:09:45Z', true, false, 'active', true, {3, 9}),
  (2, 'Apple the target audience is makes and famles aged zero and up make it pop. Can you make it look more designed this red is too red. We have big contacts we will promote you can you make it more infographic-y nor this was not according to brief can you lower the price for the website? make it high quality and please use Research can you make the font a bit bigger and change it to times new roman? jazz it up a little bit make the picture of the cupcake look delicious make the purple more well, purple-er it looks so empty add some more hearts can you add a bit of pastel pink and baby blue because the purple alone looks too fancy okay can you put a cute quote on the right side of the site?', '2021-01-26T13:58:34Z', false, true, 'active', true, {12}),
  (8, 'Hello, everyone! I''m just wondering if someone will be willing to help me out with a project? I have not dealt with Carpentry before and would love some advice on it! Heard we have a great community here.', '2021-02-02T02:29:53Z', true, false, 'active', true, {20});